#! /bin/bash
#PBS -V
#PBS -N job-dammif-array
#PBS -A ASync003
#PBS -M joanna.huang@synchrotron.org.au -m abe
#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:20:00

cd $PBS_O_WORKDIR

#---------DAMMIF------------------#
# dammif modelling in interactive mode
# to run use qsub:
# qsub -v file=FILE dammif.pbs
# where FILE is the full name of file to be used for models


dammif --prefix="$filename"_${PBS_ARRAYID} --mode=interactive --symmetry=P1 --unit=n "$filename"_dammif.out < "$filename"_0.in 
